name: Pr0xySh4rk24 Daily Config Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC; adjust as needed.
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Pr0xySh4rk24 Script
        run: |
          python pr0xySh4rk24.py --input subs.txt --output '🔒 Pr0xySh4rk 🦈.txt' -r 5 --test tcp+http
      
      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git add configsbase64.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update configsbase64.txt via GitHub Actions"

            # Fetch latest changes from remote
            git fetch origin main

            # Rebase your local branch onto the fetched remote branch
            git rebase origin/main

            # Push the rebased changes
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
