name: Pr0xySh4rkTest Daily Config Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set executable permissions for Xray-core
        run: |
          chmod +x ./xray/xray
          ls -la ./xray

      - name: Add xray folder to PATH
        run: echo "$(pwd)/xray" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests[socks]
          sudo apt-get update
          sudo apt-get install -y proxychains4 fping wget unzip

      - name: Run Pr0xySh4rkTest Script
        run: |
          # Adjust the input/output filenames and test options as needed
          python Pr0xySh4rk3.py --input subs1.txt --output Pr0xySh4rkTest.txt --test real

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Pr0xySh4rkTest.txt
          git commit -m "Update config"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push
