name: Pr0xySh4rkTest Daily Config Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC; adjust as needed.
  workflow_dispatch:

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download and Install Xray-core
        run: |
          # Download the Xray-core zip archive from the release URL.
          wget -q https://github.com/XTLS/Xray-core/releases/download/v25.3.6/Xray-linux-64.zip -O Xray.zip
          # Unzip the downloaded file.
          unzip -o Xray.zip -d xray
          # Mark the xray binary as executable.
          chmod +x xray/xray
          # Move the xray-core binary into /usr/local/bin (requires sudo privileges on ubuntu-latest).
          sudo mv xray/xray /usr/local/bin/xray

      - name: Run Pr0xySh4rkTest Script
        run: |
          # Run the script with its parameters. Adjust filenames and options as needed.
          python Pr0xySh4rk.py --input subs.txt --output Pr0xySh4rkTest.txt --test tcp+http+real

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin main
          # Pull any changes from remote to avoid conflicts.
          git pull --rebase --autostash origin main
          git add Pr0xySh4rkTest.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update Pr0xySh4rkTest.txt via GitHub Actions"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
